### ISSUE TITLE
"leavingmembers" command issue.

### ISSUE THREAD

**Issue by iMat1n** [amiralirj/Telegram-self#1]
method `get_chat_event_log` is an async generator, means it should be used with an `async for` loop :

```python
async for event in Client.get_chat_event_log(chat_id=message.chat.id ,filters =ChatEventFilter(leaving_members=True)):
    print(event)
```
Hope this helps, gl ;)

**Comment by amiralirj** [comment]
thanks for your report 
In 1.02 version method has been debugged
